# Generated by Django 4.1.9 on 2023-06-16 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import treasure.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("treasure", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.RemoveField(
            model_name="treasure",
            name="hint",
        ),
        migrations.RemoveField(
            model_name="treasure",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="treasure",
            name="treasure_description",
        ),
        migrations.RemoveField(
            model_name="treasure",
            name="treasure_name",
        ),
        migrations.AddField(
            model_name="treasure",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="treasure",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="treasure",
            name="hints",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="treasure",
            name="image",
            field=models.ImageField(null=True, upload_to=treasure.models.treasure_image_path),
        ),
        migrations.AddField(
            model_name="treasure",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="treasure",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="treasure",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="treasure",
            name="zipcode",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="treasure",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="treasure",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
